import { createHash } from "node:crypto";
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outputPath = path.join(root, "js/2mrs-data.js");
const EXPECTED_SOURCE_SHA256 = "236be982e9a172c55d483d40c38ca38b36a3dc8b8af4f402a0fd045f1b87da6f";
const EXPECTED_SOURCE_ROWS = 44599;
const H0 = 73;
const MAX_DISTANCE_MPC = 300;
const MAX_VELOCITY = H0 * MAX_DISTANCE_MPC;
const RECORD_BYTES = 7;
const SOURCE_URL = new URL("https://heasarc.gsfc.nasa.gov/xamin/query");
SOURCE_URL.search = new URLSearchParams({
  table: "twomassrsc",
  fields: "name,lii,bii,radial_velocity,ks_mag_0",
  format: "stream",
  resultmax: "50000",
  messages: "none",
  sortvar: "name",
}).toString();

function sha256(value) {
  return createHash("sha256").update(value).digest("hex");
}

function clamp(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function uint16(bytes, offset, value) {
  bytes[offset] = value >>> 8;
  bytes[offset + 1] = value & 0xff;
}

const response = await fetch(SOURCE_URL);
if (!response.ok) throw new Error(`2MRS query failed: ${response.status}`);
const source = await response.text();
const sourceHash = sha256(source);
if (sourceHash !== EXPECTED_SOURCE_SHA256) {
  throw new Error(`2MRS source changed: expected ${EXPECTED_SOURCE_SHA256}, received ${sourceHash}`);
}

const [header, ...lines] = source.trimEnd().split("\n");
if (header !== "name|lii|bii|radial_velocity|ks_mag_0") {
  throw new Error(`unexpected 2MRS header: ${header}`);
}
if (lines.length !== EXPECTED_SOURCE_ROWS) {
  throw new Error(`unexpected 2MRS row count: ${lines.length}`);
}

const rows = [];
for (const line of lines) {
  const [name, lText, bText, velocityText, magnitudeText] = line.split("|");
  const lDeg = Number(lText);
  const bDeg = Number(bText);
  const velocity = Number(velocityText);
  const magnitude = Number(magnitudeText);
  if (!velocityText || !(velocity > 0) || velocity > MAX_VELOCITY) continue;
  if (!name || !Number.isFinite(lDeg) || !Number.isFinite(bDeg)) {
    throw new Error(`invalid 2MRS row: ${line}`);
  }
  rows.push({ lDeg, bDeg, velocity, magnitude });
}

const payload = new Uint8Array(rows.length * RECORD_BYTES);
for (let i = 0; i < rows.length; i += 1) {
  const row = rows[i];
  const offset = i * RECORD_BYTES;
  uint16(payload, offset, Math.round(clamp(row.lDeg, 0, 360) / 360 * 65535));
  uint16(payload, offset + 2, Math.round((clamp(row.bDeg, -90, 90) + 90) / 180 * 65535));
  uint16(payload, offset + 4, Math.round(row.velocity));
  payload[offset + 6] = Math.round(clamp((Number.isFinite(row.magnitude) ? row.magnitude : 11.75) - 4, 0, 7.96875) * 32);
}

const payloadHash = sha256(payload);
const wrapped = Buffer.from(payload).toString("base64").match(/.{1,96}/g).join("\n");
const generated = `/**
 * Generated by scripts/build-2mrs.mjs. Do not edit by hand.
 * Compact derived subset of the public NASA HEASARC 2MRS table.
 */
export const TWOMRS_METADATA = Object.freeze(${JSON.stringify({
  catalog: "NASA HEASARC TWOMASSRSC",
  citation: "Huchra et al. 2012, ApJS 199, 26",
  source: SOURCE_URL.href,
  landingPage: "https://heasarc.gsfc.nasa.gov/w3browse/all/twomassrsc.html",
  license: "https://www.usa.gov/government-works",
  retrieved: "2026-08-22",
  sourceSha256: sourceHash,
  payloadSha256: payloadHash,
  sourceRows: lines.length,
  includedRows: rows.length,
  recordBytes: RECORD_BYTES,
  h0KmSPerMpc: H0,
  maxDistanceMpc: MAX_DISTANCE_MPC,
  selection: "finite galactic coordinates; 0 < barycentric radial velocity <= 21900 km/s",
  encoding: "big-endian uint16(l/360, (b+90)/180, velocity km/s) + uint8((Ks-4)*32)",
}, null, 2)});

export const TWOMRS_PAYLOAD_BASE64 = \`
${wrapped}
\`;
`;

await writeFile(outputPath, generated);
console.log(`wrote ${path.relative(root, outputPath)}: ${rows.length} rows, ${payload.length} bytes, sha256 ${payloadHash}`);
